version: '2'
services:
  # nginx:
  #   image: nginx
  #   links:
  #     - gogs:gogs
  #     - drone-server:drone-server
  #   volumes:
  #     - ./data/nginx/conf.d:/etc/nginx/conf.d
  #     - ./data/nginx/ssl:/etc/nginx/ssl
  #   ports:
  #     - 80:80
  #     - 443:443
  #   depends_on:
  #     - gogs
  #     - drone-server

  gogs:
    image: "gogs/gogs:0.9.141"
    volumes:
      - ./data/gogs:/data
    ports:
      - 3000:3000
    links:
      - drone-server:drone-server

  drone-server:
    image: drone/drone:0.7
    ports:
      - 8000:8000
    volumes:
      - ./data/drone7:/var/lib/drone/
    restart: always
    environment:
      - DRONE_OPEN=true
      - DRONE_GOGS=true
      - DRONE_GOGS_URL=http://gogs:3000
      - DRONE_GOGS_SKIP_VERIFY=true
      - DRONE_SECRET=BuildFun
      - DRONE_HOST=http://drone:8000

  drone-agent:
    image: drone/drone:0.7
    command: agent
    restart: always
    depends_on: [ drone-server ]
    links:
      - drone-server:drone-server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DRONE_SERVER=ws://drone-server:8000/ws/broker
      - DRONE_SECRET=BuildFun
