---
- name: Clear Lab Pipeline
  hosts: devbox
  gather_facts: no

  tasks:
    - name: docker-compose down the Pipeline
      shell: docker-compose down
      args:
        chdir: ~/ll_net_cicd_code_samples/pipeline
        executable: /bin/bash

    - name: Delete the Repo
      shell: rm -Rf ll_net_cicd_code_samples/
      args:
        chdir: ~/
        executable: /bin/bash
        removes: ~/ll_net_cicd_code_samples
